#!/usr/bin/env bash

fatal() {
	echo "$1" > /dev/stderr
	exit 1
}

get_raylib_dir() {
	if [[ "$(uname)" = "Linux" ]]; then
		echo './raylib-5.5_linux_amd64'
	elif [[ "$(uname)" = "Darwin" ]]; then
		echo './raylib-5.5_macos'
	else
		fatal "unrecognized uname $(uname)! this script doesn't work with $(uname)!"
	fi
}

get_omp_build_flags() {
	if [[ "$(uname)" = "Linux" ]]; then
		echo '-fopenmp -lomp'
	elif [[ "$(uname)" = "Darwin" ]]; then
		echo '-fopenmp -lomp'
	else
		fatal "unrecognized uname $(uname)! cannot generate openmp flags for it!"
	fi
}

raylib_dir="$(get_raylib_dir)"
[[ -d "$raylib_dir" ]] ||\
	fatal "cannot find raylib dir $raylib_dir! raylib must be present in project directory, you can run ./download_raylib to dowload it"

# sequential compilation targets use the same files as parallel targets,
# they're just compiled with different flags that don't include openmp
# meaning they will behave sequentially
# (source was made in such a way that removing omp pragmas does not alter behaviour)

# graphical targets all use parallel update logic

common_build_flags="-I./include -Wall -Wextra -Wpedantic"
omp_build_flags="$(get_omp_build_flags)"
raylib_build_flags="-I$raylib_dir/include -L$raylib_dir/lib/ -lm -lraylib"
sequential_build_flags="-DBOID_BENCHMARK $common_build_flags"
parallel_build_flags="-DBOID_BENCHMARK $common_build_flags $omp_build_flags"
graphical_build_flags="-DBOID_GRAPHICS $common_build_flags $omp_build_flags $raylib_build_flags"

common_files="./src/global-vars.c ./src/argparse.c ./src/args.c ./src/common.c"
graphics_files="./src/graphics-common.c"
benchmark_files=""
soa_files="$common_files ./src/soa.c"
aos_files="$common_files ./src/aos.c"

setup() {
	local message="$1"

	[[ -d './build' ]] || mkdir './build'
	echo "$message"
	echo 'output will be found in ./build directory'
}

# we have one function per compilation target
build_sequential_aos() {
	setup "building array of struct sequential version"
	cc -o ./build/sequential-aos $aos_files $benchmark_files src/benchmark-aos.c $sequential_build_flags
}

build_parallel_aos() {
	setup "building array of struct parallel version"
	cc -o ./build/parallel-aos $aos_files $benchmark_files src/benchmark-aos.c $parallel_build_flags
}

build_graphical_aos() {
	setup "building array of struct parallel version"
	cc -o ./build/graphical-aos $aos_files $graphics_files src/graphical-aos.c $graphical_build_flags
}

build_sequential_soa() {
	setup "building array of struct sequential version"
	cc -o ./build/sequential-soa $soa_files $benchmark_files src/benchmark-soa.c $sequential_build_flags
}

build_parallel_soa() {
	setup "building array of struct parallel version"
	cc -o ./build/parallel-soa $soa_files $benchmark_files src/benchmark-soa.c $parallel_build_flags
}

build_graphical_soa() {
	setup "building array of struct parallel version"
	cc -o ./build/graphical-soa $soa_files $graphics_files src/graphical-soa.c $graphical_build_flags
}

main() {
	# build_graphical_aos
	build_graphical_soa
}

main
